name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew assembleDebugUnitTest
